#!/usr/bin/env python3
"""Generate disposable repository graph and analysis navigation views."""

from __future__ import annotations

import argparse
import csv
import hashlib
import importlib.util
import json
import os
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
GENERATOR_PATH = "scripts/generate_analysis_views.py"
GRAPH_PATH = "views/repository-graph.json"
CURATED_VIEW_PATHS = (
    ("Sourceと派生Reasoning Chain", "02_analysis/views/reasoning-chain.md"),
    ("MobiusによるHypothesis一覧", "02_analysis/views/mobius-hypothesis-map.md"),
)
OUTPUT_PATHS = (
    "02_analysis/README.md",
    "02_analysis/views/session-hypotheses.md",
    "02_analysis/views/practice-hypotheses.md",
    "02_analysis/views/validation-status.md",
    "02_analysis/views/node-catalog.md",
    GRAPH_PATH,
)
SOURCE_GLOBS = (
    "01_working/raw-notes/*.md",
    "02_analysis/observations/*.md",
    "02_analysis/hypothesis-episodes/*.md",
    "02_analysis/patterns/*.md",
    "03_artifacts/**/*.md",
    "04_decisions/risk-decisions/*.md",
    "10_external-inputs/**/*.md",
)
LEVEL_ORDER = {"value": 0, "solution": 1, "feature": 2, "not_assessed": 3}
LEVEL_LABEL = {
    "value": "Discovery / Value",
    "solution": "Decision / Solution",
    "feature": "Delivery / Feature",
    "not_assessed": "未分類",
}
GENERATED_NOTICE = (
    "<!-- Generated by scripts/generate_analysis_views.py. "
    "Do not edit directly. -->"
)


def load_validator_module() -> Any:
    """Load the repository's canonical Markdown parsers without dependencies."""
    module_path = Path(__file__).with_name("validate_repository.py")
    spec = importlib.util.spec_from_file_location("repository_validator", module_path)
    if not spec or not spec.loader:
        raise RuntimeError(f"cannot load validator module: {module_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


VALIDATOR = load_validator_module()


def source_paths(root: Path) -> list[Path]:
    """Return authoritative Markdown sources in stable path order."""
    paths: set[Path] = set()
    for pattern in SOURCE_GLOBS:
        for path in root.glob(pattern):
            if path.is_file() and path.name != "README.md":
                paths.add(path)
    return sorted(paths, key=lambda path: path.relative_to(root).as_posix())


def partition_projectable_sources(
    root: Path, paths: list[Path],
) -> tuple[list[Path], dict[str, int]]:
    """Exclude unsafe or malformed Raw Notes using path as the trust boundary."""
    projectable: list[Path] = []
    excluded: Counter[str] = Counter()
    for path in paths:
        fields, _ = VALIDATOR.parse_frontmatter(path)
        relative_parts = path.relative_to(root).parts
        in_raw_note_directory = relative_parts[:2] == (
            "01_working",
            "raw-notes",
        )
        declares_raw_note = fields.get("type") == "raw_note"
        if not in_raw_note_directory and not declares_raw_note:
            projectable.append(path)
            continue
        if not in_raw_note_directory or VALIDATOR.validate_raw_note_for_projection(path):
            excluded["raw_note_invalid_metadata"] += 1
            continue
        if fields.get("sanitization_status") in {"not_needed", "sanitized"}:
            projectable.append(path)
            continue
        excluded["raw_note_sanitization_not_reviewed"] += 1
    return projectable, dict(sorted(excluded.items()))


def source_digest(root: Path, paths: list[Path]) -> str:
    """Hash source paths and bytes so generated projections are reproducible."""
    digest = hashlib.sha256()
    for path in paths:
        digest.update(path.relative_to(root).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def first_heading(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem


def parse_list(path: Path, field_name: str) -> list[str]:
    """Parse a flat YAML list from frontmatter, including kebab-case values."""
    lines = path.read_text(encoding="utf-8").splitlines()
    try:
        end = lines.index("---", 1)
    except (ValueError, IndexError):
        return []
    scalar_pattern = re.compile(rf"^{re.escape(field_name)}:\s*(\[.*\])\s*$")
    for line in lines[1:end]:
        scalar_match = scalar_pattern.match(line)
        if not scalar_match:
            continue
        content = scalar_match.group(1)[1:-1].strip()
        if not content:
            return []
        if any(character in content for character in "[]{}"):
            raise ValueError(f"{path}: {field_name} must be a flat YAML list")
        values = next(csv.reader([content], skipinitialspace=True))
        return [value.strip().strip("\"'") for value in values if value.strip()]

    values: list[str] = []
    in_field = False
    for line in lines[1:end]:
        if line == f"{field_name}:":
            in_field = True
            continue
        if in_field and line and not line.startswith((" ", "\t")):
            break
        match = re.match(r"^\s+-\s+(.+?)\s*$", line)
        if in_field and match:
            values.append(match.group(1).strip().strip("\"'"))
    return values


def component_projection(component: dict[str, str]) -> dict[str, Any]:
    evidence = component["Evidence refs"]
    return {
        "id": component["ID"],
        "uncertainty": component["Uncertainty"],
        "decision_importance": component["Decision importance"],
        "evidence_refs": []
        if evidence == "none"
        else [value.strip() for value in evidence.split(",") if value.strip()],
        "coverage_state": component["Coverage state"],
        "finding": component["Finding"],
        "applicability": component["Applicability"],
        "residual_uncertainty": component["Residual uncertainty"],
    }


def node_projection(root: Path, path: Path) -> dict[str, Any]:
    fields, _ = VALIDATOR.parse_frontmatter(path)
    relative_path = path.relative_to(root).as_posix()
    node_type = fields.get("type") or "artifact"
    node_id = fields.get("id")
    key = node_id or f"artifact:{relative_path}"
    node: dict[str, Any] = {
        "key": key,
        "id": node_id,
        "type": node_type,
        "title": fields.get("title") or first_heading(path),
        "path": relative_path,
        "content_language": fields.get("content_language"),
    }
    scalar_fields = (
        "created_at",
        "created_by",
        "status",
        "review_status",
        "sanitization_status",
        "confidence",
        "hypothesis_scope",
        "hypothesis_level",
        "decision_status",
        "target_node",
        "target_component_id",
        "risk_response",
        "decision_sufficiency",
        "adopted_at",
        "adopted_by",
        "scope",
    )
    for field_name in scalar_fields:
        value = fields.get(field_name)
        if value:
            node[field_name] = value
    for field_name in ("knowledge_basis", "tags"):
        values = parse_list(path, field_name)
        if values:
            node[field_name] = values
    if node_type == "hypothesis_episode":
        node["result"] = VALIDATOR.parse_hypothesis_result(path)
        approach, _ = VALIDATOR.parse_validation_approach(path)
        if approach:
            node["validation_approach"] = approach
        disposition, _ = VALIDATOR.parse_validation_disposition(path)
        if disposition:
            node["validation_disposition"] = disposition
        components, _ = VALIDATOR.parse_validation_components(path)
        node["validation_components"] = [
            component_projection(components[component_id])
            for component_id in sorted(
                components, key=lambda value: int(value.removeprefix("U"))
            )
        ]
    return {key: value for key, value in node.items() if value is not None}


def build_graph(root: Path = ROOT) -> dict[str, Any]:
    all_paths = source_paths(root)
    paths, excluded_sources = partition_projectable_sources(root, all_paths)
    nodes = [node_projection(root, path) for path in paths]
    path_by_key = {node["key"]: root / node["path"] for node in nodes}
    projected_keys = set(path_by_key)
    excluded_edges: Counter[str] = Counter()
    edges: list[dict[str, str]] = []
    for node in nodes:
        for relation_type, target in VALIDATOR.parse_relations(path_by_key[node["key"]]):
            if target not in projected_keys:
                excluded_edges["target_not_projected"] += 1
                continue
            edge = {"source": node["key"], "type": relation_type, "target": target}
            if relation_type == "evaluates" and node.get("target_component_id"):
                edge["target_component_id"] = node["target_component_id"]
            edges.append(edge)
    edges.sort(
        key=lambda edge: (
            edge["source"],
            edge["type"],
            edge["target"],
            edge.get("target_component_id", ""),
        )
    )
    return {
        "schema_version": 3,
        "projection": {
            "authority": "none",
            "description": (
                "Disposable navigation projection generated from repository Markdown; "
                "source nodes and adopted artifacts remain authoritative."
            ),
            "generator": GENERATOR_PATH,
            "source_digest": source_digest(root, paths),
            "excluded_sources": excluded_sources,
            "excluded_edges": dict(sorted(excluded_edges.items())),
        },
        "nodes": nodes,
        "edges": edges,
    }


def md_link(label: str, from_path: str, to_path: str) -> str:
    source_directory = Path(from_path).parent
    target = Path(to_path)
    relative = Path(os.path.relpath(target, source_directory))
    safe_label = (
        label.replace("\\", "\\\\")
        .replace("[", "\\[")
        .replace("]", "\\]")
        .replace("|", "\\|")
        .replace("\n", " ")
    )
    return f"[{safe_label}]({relative.as_posix()})"


def node_link(node: dict[str, Any], output_path: str) -> str:
    return md_link(node["title"], output_path, node["path"])


def graph_nodes_by_type(graph: dict[str, Any]) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for node in graph["nodes"]:
        grouped[node["type"]].append(node)
    return grouped


def render_hypothesis_view(graph: dict[str, Any], scope: str, output_path: str) -> str:
    nodes = {node["key"]: node for node in graph["nodes"]}
    hypotheses = [
        node
        for node in graph["nodes"]
        if node["type"] == "hypothesis_episode"
        and node.get("hypothesis_scope") == scope
    ]
    hypotheses.sort(
        key=lambda node: (
            LEVEL_ORDER.get(node.get("hypothesis_level", "not_assessed"), 99),
            node["id"],
        )
    )
    parents: dict[str, list[str]] = defaultdict(list)
    for edge in graph["edges"]:
        if edge["type"] == "tests":
            parents[edge["source"]].append(edge["target"])
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {scope.capitalize()} scopeのHypothesis",
        "",
        "このViewはfrontmatterと直接relationのみから生成したNavigationです。",
        "Evidence、解釈、検証結果または採用判断の正本ではありません。",
        "",
        "| Level | Hypothesis Episode | Status | Result | Direct parent |",
        "| --- | --- | --- | --- | --- |",
    ]
    for node in hypotheses:
        parent_links = [
            node_link(nodes[parent], output_path)
            for parent in sorted(parents.get(node["key"], []))
            if parent in nodes
        ]
        lines.append(
            "| {level} | {node} | `{status}` | `{result}` | {parents} |".format(
                level=LEVEL_LABEL.get(node.get("hypothesis_level"), "未分類"),
                node=node_link(node, output_path),
                status=node.get("status", "unknown"),
                result=node.get("result", "unknown"),
                parents="、".join(parent_links) or "なし",
            )
        )
    if not hypotheses:
        lines.append("| - | 対象Nodeなし | - | - | - |")
    lines.extend(
        [
            "",
            "`tests`は同じscope内の直上Hierarchy Parentだけを表します。",
            "子Nodeの結果は親Nodeへ推移しません。",
            "",
        ]
    )
    return "\n".join(lines)


def coverage_summary(components: list[dict[str, Any]]) -> str:
    counts = Counter(component["coverage_state"] for component in components)
    order = ("checked_for_current_scope", "partially_checked", "not_checked")
    return "、".join(f"`{state}` {counts[state]}" for state in order if counts[state])


def render_validation_view(graph: dict[str, Any], output_path: str) -> str:
    current_decisions: dict[tuple[str, str], list[dict[str, Any]]] = defaultdict(list)
    for node in graph["nodes"]:
        if node["type"] == "risk_decision" and node.get("decision_status") == "current":
            current_decisions[(node.get("target_node", ""), node.get("target_component_id", ""))].append(node)
    hypotheses = sorted(
        (node for node in graph["nodes"] if node["type"] == "hypothesis_episode"),
        key=lambda node: (node.get("hypothesis_scope", ""), node["id"]),
    )
    lines = [
        GENERATED_NOTICE,
        "",
        "# Hypothesisの検証状況",
        "",
        "このViewは、宣言済みの結果、Evidence Coverage、現在のRisk Decisionを",
        "機械的に並べたNavigationです。未記録のDecisionを対応漏れとは解釈しません。",
        "",
        "| Hypothesis Episode | Scope | Approach | Result | Disposition | Components | Coverage | Current Risk Decisions |",
        "| --- | --- | --- | --- | --- | ---: | --- | ---: |",
    ]
    for node in hypotheses:
        components = node.get("validation_components", [])
        decision_count = sum(
            len(current_decisions.get((node["id"], component["id"]), []))
            for component in components
        )
        lines.append(
            "| {node} | `{scope}` | {approach} | `{result}` | {disposition} | {count} | {coverage} | {decisions} |".format(
                node=node_link(node, output_path),
                scope=node.get("hypothesis_scope", "unknown"),
                approach=(
                    f"`{node['validation_approach']}`"
                    if node.get("validation_approach")
                    else "—"
                ),
                result=node.get("result", "unknown"),
                disposition=(
                    f"`{node['validation_disposition']}`"
                    if node.get("validation_disposition")
                    else "—"
                ),
                count=len(components),
                coverage=coverage_summary(components) or "なし",
                decisions=decision_count,
            )
        )
    lines.extend(
        [
            "",
            "DispositionはEpisodeの次の扱いであり、仮説の真偽やRisk受容ではありません。",
            "Coverageは仮説が正しい割合ではありません。Risk Decisionは仮説の支持、",
            "AnalysisのReview、Artifact採用のいずれも代替しません。",
            "",
        ]
    )
    return "\n".join(lines)


def render_catalog(graph: dict[str, Any], output_path: str) -> str:
    catalog_types = ("observation", "hypothesis_episode", "pattern")
    lines = [
        GENERATED_NOTICE,
        "",
        "# Analysis Node一覧",
        "",
        "この一覧はNodeの宣言済みmetadataのみを表示します。",
        "",
        "| Type | Node | Status | Knowledge Basis | Confidence |",
        "| --- | --- | --- | --- | --- |",
    ]
    nodes = sorted(
        (node for node in graph["nodes"] if node["type"] in catalog_types),
        key=lambda node: (catalog_types.index(node["type"]), node.get("id", "")),
    )
    for node in nodes:
        basis = "、".join(f"`{value}`" for value in node.get("knowledge_basis", [])) or "なし"
        lines.append(
            "| `{type}` | {node} | `{status}` | {basis} | `{confidence}` |".format(
                type=node["type"],
                node=node_link(node, output_path),
                status=node.get("status", "unknown"),
                basis=basis,
                confidence=node.get("confidence", "unknown"),
            )
        )
    lines.append("")
    return "\n".join(lines)


def render_index(graph: dict[str, Any], output_path: str, root: Path = ROOT) -> str:
    grouped = graph_nodes_by_type(graph)
    accepted_artifacts = sorted(
        (
            node
            for node in grouped.get("artifact", [])
            if node.get("status") == "accepted"
        ),
        key=lambda node: node["path"],
    )
    counts = [
        ("Raw Note", len(grouped.get("raw_note", []))),
        ("External Input", len(grouped.get("external_input", []))),
        ("Observation", len(grouped.get("observation", []))),
        ("Hypothesis Episode", len(grouped.get("hypothesis_episode", []))),
        ("Pattern", len(grouped.get("pattern", []))),
        ("Risk Decision", len(grouped.get("risk_decision", []))),
        ("Accepted Artifact", len(accepted_artifacts)),
    ]
    lines = [
        GENERATED_NOTICE,
        "",
        "# 分析",
        "",
        "このREADMEと配下のViewは、既存Nodeを見つけて直接relationを追うための",
        "再生成可能なNavigationです。Evidence、派生Claim、採用判断、現在の正本ではありません。",
        "正本はリンク先のNodeと採用済みArtifactです。",
        "",
        "## Repository snapshot",
        "",
        "| Node type | Count |",
        "| --- | ---: |",
    ]
    lines.extend(f"| {label} | {count} |" for label, count in counts)
    excluded_raw_notes = sum(
        count
        for reason, count in graph["projection"]["excluded_sources"].items()
        if reason.startswith("raw_note_")
    )
    if excluded_raw_notes:
        lines.extend(
            [
                "",
                "Publication-safety未確認のRaw Note "
                f"{excluded_raw_notes}件はProjectionから除外されています。",
            ]
        )
    lines.extend(
        [
            "",
            f"Source digest: `{graph['projection']['source_digest']}`",
            "",
            "## 採用済みArtifact",
            "",
        ]
    )
    if accepted_artifacts:
        lines.extend(f"- {node_link(node, output_path)}" for node in accepted_artifacts)
    else:
        lines.append("- なし")
    curated_views = [
        (label, path) for label, path in CURATED_VIEW_PATHS if (root / path).is_file()
    ]
    if curated_views:
        lines.extend(
            [
                "",
                "## 詳細Navigation Views",
                "",
                "次のViewは、Nodeへのlinkを保った非同期のRepository-authored解説です。",
                "鮮度確認の対象ではなく、Evidenceまたは現在の正本でもありません。",
                "",
            ]
        )
        lines.extend(
            f"- {md_link(label, output_path, path)}" for label, path in curated_views
        )
    lines.extend(
        [
            "",
            "## Analysis Views",
            "",
            f"- {md_link('Session scopeのHypothesis', output_path, '02_analysis/views/session-hypotheses.md')}",
            f"- {md_link('Practice scopeのHypothesis', output_path, '02_analysis/views/practice-hypotheses.md')}",
            f"- {md_link('Hypothesisの検証状況', output_path, '02_analysis/views/validation-status.md')}",
            f"- {md_link('Analysis Node一覧', output_path, '02_analysis/views/node-catalog.md')}",
            f"- {md_link('Repository Graph JSON', output_path, GRAPH_PATH)}",
            "",
            "## 読み方",
            "",
            "- `session`と`practice`のHypothesis階層を混ぜない。",
            "- `tests`は同一scopeの直上Parentだけを示し、結果は推移しない。",
            "- `knowledge_basis`、Intent Review、検証結果、Evidence Coverage、",
            "  Risk Decision、Artifact採用を別の軸として読む。",
            "- 自動生成Viewにない解釈が必要な場合は、正本Nodeを直接確認する。",
            "",
            "## 再生成",
            "",
            "```text",
            "python3 scripts/generate_analysis_views.py",
            "python3 scripts/generate_analysis_views.py --check",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def render_outputs(root: Path = ROOT) -> dict[str, str]:
    graph = build_graph(root)
    return {
        "02_analysis/README.md": render_index(
            graph, "02_analysis/README.md", root
        ),
        "02_analysis/views/session-hypotheses.md": render_hypothesis_view(
            graph, "session", "02_analysis/views/session-hypotheses.md"
        ),
        "02_analysis/views/practice-hypotheses.md": render_hypothesis_view(
            graph, "practice", "02_analysis/views/practice-hypotheses.md"
        ),
        "02_analysis/views/validation-status.md": render_validation_view(
            graph, "02_analysis/views/validation-status.md"
        ),
        "02_analysis/views/node-catalog.md": render_catalog(
            graph, "02_analysis/views/node-catalog.md"
        ),
        GRAPH_PATH: json.dumps(graph, ensure_ascii=False, indent=2) + "\n",
    }


def stale_outputs(root: Path = ROOT) -> list[str]:
    expected = render_outputs(root)
    stale: list[str] = []
    for relative_path, content in expected.items():
        path = root / relative_path
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            stale.append(relative_path)
    return stale


def write_outputs(root: Path = ROOT) -> None:
    for relative_path, content in render_outputs(root).items():
        path = root / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail when generated views are stale"
    )
    args = parser.parse_args()
    if args.check:
        stale = stale_outputs(ROOT)
        if stale:
            for path in stale:
                print(f"stale generated view: {path}")
            return 1
        print(f"Generated views are current: {len(OUTPUT_PATHS)} file(s) checked.")
        return 0
    write_outputs(ROOT)
    print(f"Generated analysis views: {len(OUTPUT_PATHS)} file(s) written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
